pull_request_rules:
  - name: Auto-merge PRs when all checks pass
    conditions:
      - base=main
      - check-success=test
    actions:
      merge:
        method: squash
        commit_message_format:
          title: pr-title
          body: pr-body
          trailers:
            - approved-by
